module.exports = {
  brand: "SkiLuxe New Gudauri",
  brandShort: "SkiLuxe",
  tagline: "Boutique ski apartments in the Caucasus",
  domain: "new-gudauri.com",
  apiBase: "https://api.new-gudauri.com",
  email: "gudauriflats@gmail.com",
  whatsapp: "+995597718138",
  whatsappDisplay: "+995 597 71 81 38",
  instagram: "skiluxeng",
  instagramUrl: "https://www.instagram.com/skiluxeng/",
  telegram: "SkiluxeBot",
  telegramUrl: "https://t.me/SkiluxeBot",
  langs: [
    { code: "en", label: "English", dir: "ltr" },
    { code: "ru", label: "Русский", dir: "ltr" },
    { code: "ka", label: "ქართული", dir: "ltr" },
    { code: "he", label: "עברית", dir: "rtl" },
  ],
  defaultLang: "en",
  currency: "GEL",
  coords: { lat: 42.477, lng: 44.474 },
};
